#!/bin/bash
battery_percent() {
	local charge_now=$(cat /sys/class/power_supply/BAT0/charge_now)
	local charge_full=$(cat /sys/class/power_supply/BAT0/charge_full)
	local charge=$(($charge_now * 100 / $charge_full))
	echo $charge
}
battery_status() {
	local battery_charge=$(battery_percent)
	local battery_status=$(cat /sys/class/power_supply/BAT0/status)
	echo "${battery_charge}% ($battery_status)"
}
echo "Status line: $(battery_status)"

